title:              Formagine
email:              formagine@gmail.com
description:        Prototyping Pinned Down.
author:             Formagine
baseurl:            ""

# Social Profiles
twitter_username:   Formagine2020
github_username:    
facebook_username:  
instagram_username:  formagine2020
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
