title:              Formagine
email:              formagine@gmail.com
description:        In traditional vacuum forming, a positive mold, or buck, is precisely machined into the desired shape. Due to the cost of making this mold, vacuum forming is typically done for high-volume production and manufacturing. Our team began by asking the question how could we make vacuum forming a desktop process or something that could be used in rapid prototyping? The answer was removing the buck from the equation. If the buck could be remade or change dynamically to the user's needs, massive savings in money and time could be achieved. The cost of vacuum forming would fall just to the cost of the plastic.

For the past 4 months, we have been designing a device that will combine a vacuum former with a bed of actuated pins. Our idea was inspired by the MIT's inFORM Dynamic Display.
author:             Start Bootstrap
baseurl:            ""

# Social Profiles
twitter_username:   Formagine2020
github_username:    
facebook_username:  
instagram_username:  formagine2020
linkedin_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
